### ISSUE TITLE
PyQt5 on Pypi does not contain QAxContainer

### ISSUE THREAD

**Issue by machbio** [softage0/algorithm-trading-webapp#1]
Installlation issues with below problem

```
ImportError: No module named 'PyQt5.QAxContainer'
```

**Comment by softage0** [comment]
QAxContainer is contained on PyQt5 package on **Windows** platform only since it uses 'ocx' module.
As I mentioned on README, this project only works on Windows platform.

If you met this issue on Windows, please let me know.
